# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4d5f0bea80d06bc5c49f0088486345fbf1baf3cf93b270869871f69fe056c7c120db1daffeed6fc213bcf6ee860c2eeacb441b126bdafc7f66ba26c6992bf01

test:
  secret_key_base: 81476c227bcbe15edcaf393aa65f8eec5a4705eb55e5917b91e6b1d75698b0363369c5584c4b6c08c0becd6c86b78904cc7401ceca894d38a9cc1955644d0081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
